fix failed compilation due to lookup_in v5.11
Linux commit 4e7b5671c6a8 ("block: remove i_bdev") changed function
lookup_bdev():

-struct block_device *lookup_bdev(const char *pathname)
+int lookup_bdev(const char *pathname, dev_t *dev)

And APFS module commit 3a2e3369d251 ("Take exclusive ownership of block
device on mount") didn't notice the change. It causes failed compilation
in v5.11 and later:

=======================================================================
/root/rw/super.c:1128:29: error: too few arguments to function call,
expected 2, have 1
        bdev = lookup_bdev(dev_name);
                       ~~~~~~~~~~~ ^
./include/linux/blkdev.h:1984:5: note: 'lookup_bdev' declared here
int lookup_bdev(const char *pathname, dev_t *dev);
        ^
        1 error generated.
=======================================================================

Introduce new version apfs_nx_find_by_dev() for v5.11 and let
apfs_attach_nxi() call new version lookup_bdev().

Signed-off-by: Su Yue <l@damenly.su>
[ernesto: implement apfs_lookup_bdev() and use new apfs_nx_find_by_dev()
          for all kernel versions]
Signed-off-by: Ernesto A. Fernández <ernesto@corellium.com>