apfs: fix failed compilation due to idmap mount changes in v5.12
Since kernel commit 549c7297717c ("fs: make helpers idmap mount aware")
extended the exisiting inode method to let filesystems be aware of
idmapped mounts, compiling apfs module with linux v5.12 failed:

========================================================================
make
make -C /lib/modules/5.12.0-custom/build M=/root/rw
make[1]: Entering directory '/root/linux'
  CC [M]  /root/linux-apfs-rw/dir.o
/root/linux-apfs-rw/dir.c:644:5: error: conflicting types for apfs_mknod
  644 | int apfs_mknod(struct inode *dir, struct dentry *dentry, umode_t mode, dev_t rdev)
      |     ^~~~~~~~~~
In file included from /root/linux-apfs-rw/dir.c:8:
/root/linux-apfs-rw/apfs.h:642:12: note: previous declaration of apfs_mknod was here
  642 | extern int apfs_mknod(struct user_namespace *mnt_userns, struct inode *dir,
      |            ^~~~~~~~~~
/root/linux-apfs-rw/dir.c:649:5: error: conflicting types for apfs_mkdir
  649 | int apfs_mkdir(struct inode *dir, struct dentry *dentry, umode_t mode)
      |     ^~~~~~~~~~
In file included from /root/linux-apfs-rw/dir.c:8:
/root/linux-apfs-rw/apfs.h:644:12: note: previous declaration of apfs_mkdir was here
  644 | extern int apfs_mkdir(struct user_namespace *mnt_userns, struct inode *dir,
      |            ^~~~~~~~~~
/root/linux-apfs-rw/dir.c:654:5: error: conflicting types for apfs_create
  654 | int apfs_create(struct inode *dir, struct dentry *dentry, umode_t mode,
      |     ^~~~~~~~~~~
In file included from /root/linux-apfs-rw/dir.c:8:
/root/linux-apfs-rw/apfs.h:649:12: note: previous declaration of apfs_create was here
  649 | extern int apfs_create(struct user_namespace *mnt_userns, struct inode *dir,
      |            ^~~~~~~~~~~
/root/linux-apfs-rw/dir.c:1197:5: error: conflicting types for apfs_rename
 1197 | int apfs_rename(struct inode *old_dir, struct dentry *old_dentry,
      |     ^~~~~~~~~~~
In file included from /root/linux-apfs-rw/dir.c:8:
/root/linux-apfs-rw/apfs.h:646:12: note: previous declaration of apfs_rename was here
  646 | extern int apfs_rename(struct user_namespace *mnt_userns, struct inode *old_dir,
      |            ^~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:271: /root/linux-apfs-rw/dir.o] Error 1
make[1]: *** [Makefile:1851: /root/rw] Error 2
make[1]: Leaving directory '/root/linux'
make: *** [Makefile:14: default] Error 2
========================================================================

Although keeping forward and backward compatibilities is painful,
add awful preprocessors to let compilation pass.

Signed-off-by: Su Yue <l@damenly.su>